name: radioramezan
description: A streaming radio service during Ramadan for Iranians living abroad

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_nav_bar: ^5.0.3
  http: ^0.12.2
  preload_page_view: ^0.1.5
  flutter_holo_date_picker: ^0.3.2 # do not update
  intl: ^0.17.0
  geolocator: ^6.2.1
  google_maps_flutter: ^2.0.3
  vector_math: ^2.0.8
  assets_audio_player: ^2.0.15
  flutter_settings_screens: ^0.2.2 # do not update
  url_launcher: ^6.0.3
  cupertino_icons: ^1.0.2
  package_info_plus: '>=0.6.3 <2.0.0'
  shamsi_date: ^0.12.0
  carousel_slider: ^3.0.0
  dynamic_theme: ^1.0.1
  flutter_downloader: ^1.5.2
  share: ^2.0.1
  cron: ^0.3.0
  mailer: ^5.0.0
  draggable_scrollbar: ^0.1.0
  permission_handler: ^5.1.0+2
  timezone: ^0.7.0
  # flutter_analog_clock: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "icons/icon-512x512.png"
#   adaptive_icon_foreground: "icons/adaptive-foreground-512x512.png"
#   adaptive_icon_background: "icons/adaptive-background-512x512.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Tahrir
      fonts:
        - asset: fonts/tahrir_book.ttf
          weight: 300
        - asset: fonts/tahrir_regular.ttf
          weight: 400
        - asset: fonts/tahrir_medium.ttf
          weight: 500
        - asset: fonts/tahrir_bold.ttf
          weight: 600
        - asset: fonts/tahrir_extra_bold.ttf
          weight: 700
        - asset: fonts/tahrir_black.ttf
          weight: 800
    - family: Sans
      fonts:
        - asset: fonts/sans_mobile_ultraLight.ttf
          weight: 200
        - asset: fonts/sans_mobile_light.ttf
          weight: 300
        - asset: fonts/sans_mobile.ttf
          weight: 400
        - asset: fonts/sans_mobile_medium.ttf
          weight: 500
        - asset: fonts/sans_mobile_bold.ttf
          weight: 600
        - asset: fonts/sans_mobile_black.ttf
          weight: 700

  assets:
    - audios/
    - fonts/
    - icons/
    - images/
    - texts/

# flutter_native_splash:
#   color: "#822C61"
#   image: "images/logo_white_transparent_background_large.png"
